### PR TITLE
Add support of Homematic Control Unit (HCU)

### PR DESCRIPTION
**Pull request by dietzm**
Requires the accesspoint id to be passed in the header and data.
With this patch auth tokens can be successfully created with HCU

### CODE REVIEW

**Comment by dietzm** [comment]
issue #542

**Comment by hahn-th** [comment]
LGTM 👍 
Thank you!!

**Comment by SukramJ** [comment]
Didn't you want to merge that?

**Comment by hahn-th** [comment]
I thought i did.... ? Could Look After it tomorrow or later that day

**Comment by hahn-th** [comment]
You were right... sorry for the upsi. Merged it and make a new release 1.1.5

**Pull request merged**
