### PR TITLE
Add hue support

### PR DESCRIPTION
**Pull request by hahn-th**

### CODE REVIEW

**Comment by crohot** [comment]
Setting up the HmIP-Hue-Connection blocked communication between Home Assistant and HmIP Cloud. Not only for me. Will this be solved with this update?

**Comment by hahn-th** [comment]
With Version 1.0.11 it has been solved. But there is no control over hue devices so far. To get this done i need help.

**Comment by crohot** [comment]
To be honest, i wouldn´t invest too much time for now. First, this is looking like a test by EQ-3 to me, second, users with Hue will already have that running in Home Assistant with one of the other solutions. What do you think?

**Comment by hahn-th** [comment]
I personally think the same. Let's see what EQ3 will do with the app in the future. This updated layed the foundation for more integrations in the future by implementing the "deviceArchetype". On the other hand, the homematic app is not that good as i would like use it for controling everything.

**Pull request merged**
